openapi: 3.0.0
info:
  title: 'E-commerce API'
  description: 'API documentation for the E-commerce project'
  contact:
    email: support@yourapi.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  version: 1.0.0
